<?php

/**
 * @file
 * Primary module hooks for Artsci Search module.
 */

/**
 * Implements hook_theme().
 */
function artsci_search_theme($existing, $type, $theme, $path) {
  $artsci_search_config = \Drupal::config('artsci_search.settings');
  return [
    'artsci_search' => [
      'variables' => [
        'config' => $artsci_search_config->get('artsci_search'),
        'search_form' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function artsci_search_page_attachments(&$page) {
  $admin_context = \Drupal::service('router.admin_context');
  if (!$admin_context->isAdminRoute()) {
    $page['#attached']['library'][] = 'artsci_search/search-form';
  }
}
