# config/schema/atomic_artsci.schema.yml

atomic_artsci.settings:
  type: config_object
  label: 'Atomic Artsci theme settings'
  mapping:
    header:
      type: mapping
      label: 'Header settings'
      mapping:
        type:
          type: string
          label: 'Site name display'
        nav_style:
          type: string
          label: 'Header navigation style'
        sticky:
          type: boolean
          label: 'Sticky header'
        toppage:
          type: boolean
          label: 'Back to top button'
        footer_logo:
          type: boolean
          label: 'Footer logo'
        top_links_limit:
          type: integer
          label: 'Top links limit'
    fonts:
      type: mapping
      label: 'Font settings'
      mapping:
        font-family:
          type: string
          label: 'Font family'
    footer:
      type: mapping
      label: 'Footer settings'
      mapping: {}
