<?php

/**
 * @file
 * Contains hook implementations for Artsci Media WYSIWYG.
 */

use Drupal\Component\Utility\Html;
use Drupal\Component\Utility\UrlHelper;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\file\Entity\File;
use Drupal\image\Entity\ImageStyle;
use Drupal\artsci_media_wysiwyg\Plugin\media\Source\Panopto;

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 */
function artsci_media_wysiwyg_inline_entity_form_entity_form_alter(&$entity_form, &$form_state) {
  if ($entity_form["#entity_type"] === 'media' && $entity_form["#bundle"] === 'file') {
    if ($entity_form["#op"] === 'add') {
      $entity_form["revision_log_message"]["#access"] = FALSE;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function artsci_media_wysiwyg_form_fontawesome_icon_dialog_alter(&$form, FormStateInterface $form_state, $form_id) {
  artsci_core_configure_fontawesome_icon_field($form);
  $form['#attached']['library'][] = 'artsci_core/claro-exposed-form';
}

/**
 * Implements hook_form_FORMID_alter().
 */
function artsci_media_wysiwyg_form_editor_media_dialog_alter(&$form, FormStateInterface $form_state) {
  if (isset($form['view_mode']) && isset($form['view_mode']['#options']) && isset($form['view_mode']['#options']['default'])) {
    $form['view_mode']['#options']['default'] = t('Original');
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function artsci_media_wysiwyg_form_media_library_add_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'artsci_media_wysiwyg/media_overrides';
}


/**
 * Implements hook_config_schema_info_alter().
 */
function artsci_media_wysiwyg_config_schema_info_alter(&$definitions) {
  // Opt-out of the SourceEditingRedundantTags constraint in CKEditor5 from
  // https://www.drupal.org/project/drupal/issues/3410100#comment-15457015.
  if (isset($definitions['ckeditor5.plugin.ckeditor5_sourceEditing'])) {
    unset($definitions['ckeditor5.plugin.ckeditor5_sourceEditing']['mapping']['allowed_tags']['sequence']['constraints']['SourceEditingRedundantTags']);
  }
}

/**
 * Implements hook_library_info_alter().
 */
function artsci_media_wysiwyg_library_info_alter(&$libraries, $extension) {
  if ($extension === 'ckeditor5' && isset($libraries['internal.drupal.ckeditor5'])) {
    $libraries['internal.drupal.ckeditor5']['dependencies'][] = 'artsci_media_wysiwyg/ckeditor5-a11y';
  }
}
