terminus site:upstream:set wustl-forms	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-artsciportal 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-biology 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-eeps 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-humanities 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-insideartsci 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-itartsci   	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-afas "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-anthropology "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-buildingartsci "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-chemistry "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-classics "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-ealc "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-graduation "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-holdthatthought "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-jimes "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-lasprogram "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-rll "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-slavery "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-artsci "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-amcs "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-arthistory "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-artsciadvising "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-complitandthought "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-education "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-enst "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-fms "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-forms "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-globalstudies "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-hdw "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-history "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-pad "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-precollege "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-psych "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-wc "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-collegewriting "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-fellowshipsoffice 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-forms.artsci 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-immersivetech 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-linguistics 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-literacies 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-literaryarts 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-movingstories 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-music 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-overseas 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-philosophy 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-pnp 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-prehealth 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-publichealthandsociety 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-quantumleaps 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-religiousstudies 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-sociology 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-strategicplan.artsci 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-summersession 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-transdisciplinaryfutures 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-triads 	"WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-polisci "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-johnmaxwulfing "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-olympian "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-artscistage "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-artsci-nu "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-economics "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-english "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-gradstudies "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-math "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-mcss "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-mindfulness "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-myprehealth "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-physics "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-postbaccpremed "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-sds "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-strategicplan "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-undergradresearch "WashU Deps Arts and Science D10" --yes
terminus site:upstream:set wustl-wgss "WashU Deps Arts and Science D10" --yes
